### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by dualznz** [Havenstd06/laravel-plex#1]
Hi, i would like to know if you can upgrade the package to support laravel 10?

**Comment by JamSousa** [comment]
Please update to version 10 <3

**Comment by Havenstd06** [comment]
I've upgraded to php8.1 minimum. But what do you mean by upgrading to Laravel 10? What's not compatible?

**Comment by JamSousa** [comment]
version of laravel 10 is not compatible because of illuminate/support which is one version up.

I'm following your work with this project and your work is incredible, congratulations

**Comment by Havenstd06** [comment]
You're right, my bad! I updated! Thanks!
